language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.1
install:
  - sudo apt-get install python-gdal
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
#  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -r requirements/localdev.txt --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=W404,E501,E128,W292,E122,E124 src"
#  - pyflakes -x W src
script:
  - PYTHONPATH=src django-admin.py test --settings=ashtag.settings.testing
